### PR TITLE
QRDA Export Not Handling Relevant DateTime/Period Accurately

### PR DESCRIPTION
**Pull request by adongare**
QRDA Export Not Handling Relevant DateTime/Period Accurately
- if relevantPeriod is null or both low and high are null, then check relevantDateTime
- If both relevantPeriod & relevantDateTime are null, <effectiveTime nullFlavor='UNK'/ 
 
Pull requests into cqm-parsers require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] Internal ticket for this PR:
- [ ] Internal ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Review by serhii-ilin — APPROVED** [review]

**Comment by adongare** [comment]
@dczulada don't think we can run ruby 2.3, 2.4 builds anymore. cqm-validators expects ruby >= 2.5 
Should I remove 2.3, 2.4 builds?

**Comment by dczulada** [comment]
@adongare I'm OK with removing the older ruby versions.

I'm also onboard with this approach for addressing exporting a scenario with a RelevantPeriod with a null Low and High value.  Without out this workaround, there is no way to export a relevant Datetime from Bonnie.

However, I believe this is actually more of an issue with Bonnie allowing for the entry of both RelevantPeriod and RelevantDateTime.

-Dave

**Comment by adongare** [comment]
@dczulada right, this is an issue in bonnie. it allows both relevatDateTime and relevatPeriod. I had a discussion with SMEs regarding making it mutually exclusive however they want to allow both

**Comment by adongare** [comment]
Sorry, I missed your edits:

> Technically, an interval can have a low and high of null. However, I do not believe this is what Measure Developers intend on testing with the uncheck both low and high values in the UI.
> https://cql.hl7.org/04-logicalspecification.html#interval

That is happening because of the way interval widget implemented. Interval is created even if there is no `low` and `high`
https://github.com/MeasureAuthoringTool/bonnie/blob/d9e9a9925c99fc22a2789b8f9a1a8cbeb3ea5a4d/app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee#L81

This can be fixed by updating this widget as well. If low and high both null, set whole interval object to null instead of creating interval with `low=null` and `high=null`  but I'm not sure whether this is right way to create interval(because like you mentioned low and high both can be null)
Please let me know your thoughts.

**Comment by dczulada** [comment]
@adongare 

I think an ideal approach would be this.

Step 1) Update cqm-reports in the manner that you've proposed here.

Step 2) Propose updating Bonnie UI to allow a user to select either 'relevantPeriod' or 'relevantDatetime'.  This way a user can intentionally test a scenario with a null start and end point.
Step 3) If users accept approach (in step 3), revert cqm-reports to previous behavior.

**Review by dczulada — APPROVED** [review]

**Comment by adongare** [comment]
I'll propose this plan to SMEs and measure devs. Thanks Dev!

**Pull request merged**
